# AUTOGENERATED by nebula-sdks/generator. Do not edit by hand.
# Source: nebula-sdks/openapi/openapi.json

from __future__ import annotations
from typing import Any, Optional, Union
from pydantic import ValidationError
from .. import _models as models
from .._runtime import NebulaCore


class ClientResource:
    def __init__(self, core: NebulaCore) -> None:
        self._core = core

    async def health(
        self
    ) -> models.WrappedGenericMessageResponse:
        """
        Health probe
        
        Lightweight liveness probe. Returns a 200 with a fixed message when the API process is up. Does not verify downstream dependencies (database, storage, workers) — use the internal status endpoints for those.
        
        operationId: client.health
        endpoint: GET /v1/health
        """
        _raw = await self._core.request({
            "method": "GET",
            "path": "/v1/health",
            "path_params": {},
            "query": None,
            "idempotent": True,
        })
        try:
            return models.WrappedGenericMessageResponse.model_validate(_raw)
        except ValidationError:
            return _raw  # type: ignore[return-value]
