# AUTOGENERATED by nebula-sdks/generator. Do not edit by hand.
# Source: nebula-sdks/openapi/openapi.json

from __future__ import annotations
from typing import Any, Optional, Union
from pydantic import TypeAdapter, ValidationError
from .. import _models as models
from .._runtime import NebulaCore


class CollectionsResource:
    def __init__(self, core: NebulaCore) -> None:
        self._core = core

    async def create(
        self,
        body: models.CreateCollectionRequest
    ) -> models.CollectionResponse:
        """
        Create a new collection
        
        Create a new collection and automatically add the creating user
        to it.
        
        This endpoint allows authenticated users to create a new collection
        with a specified name and optional description. The user creating
        the collection is automatically added as a member.
        
        operationId: collections.create
        endpoint: POST /v1/collections
        """
        _raw = await self._core.request({
            "method": "POST",
            "path": "/v1/collections",
            "path_params": {},
            "query": None,
            "body": body,
            "idempotent": False,
        })
        _raw = _raw["results"] if isinstance(_raw, dict) else getattr(_raw, "results", _raw)
        try:
            return models.CollectionResponse.model_validate(_raw)
        except ValidationError:
            return _raw  # type: ignore[return-value]

    async def delete(
        self,
        id: str
    ) -> models.GenericBooleanResponse:
        """
        Delete collection
        
        Delete an existing collection.
        
        This endpoint allows deletion of a collection identified by its
        UUID. The user must have appropriate permissions to delete the
        collection. Deleting a collection removes all associations but does
        not delete the engrams within it.
        
        operationId: collections.delete
        endpoint: DELETE /v1/collections/{id}
        """
        _raw = await self._core.request({
            "method": "DELETE",
            "path": "/v1/collections/{id}",
            "path_params": {"id": id},
            "query": None,
            "idempotent": True,
        })
        _raw = _raw["results"] if isinstance(_raw, dict) else getattr(_raw, "results", _raw)
        try:
            return models.GenericBooleanResponse.model_validate(_raw)
        except ValidationError:
            return _raw  # type: ignore[return-value]

    async def list(
        self,
        *,
        ids: Optional[list[str]] = None,
        name: Optional[Union[str, None]] = None,
        cursor: Optional[Union[str, None]] = None,
        limit: Optional[int] = None,
        owner_only: Optional[bool] = None,
        workspace_id: Optional[Union[str, None]] = None
    ) -> models.PaginatedCollectionResponse:
        """
        List collections
        
        Returns a cursor-paginated list of collections the authenticated
        user has access to.
        
        Results can be filtered by providing specific collection IDs.
        Regular users will only see collections they own or have access to.
        Superusers can see all collections.
        
        The collections are returned in order of last modification, with
        most recent first.
        
        operationId: collections.list
        endpoint: GET /v1/collections
        """
        _raw = await self._core.request({
            "method": "GET",
            "path": "/v1/collections",
            "path_params": {},
            "query": {"ids": ids, "name": name, "cursor": cursor, "limit": limit, "owner_only": owner_only, "workspace_id": workspace_id},
            "idempotent": True,
        })
        try:
            return models.PaginatedCollectionResponse.model_validate(_raw)
        except ValidationError:
            return _raw  # type: ignore[return-value]

    async def retrieve(
        self,
        id: str
    ) -> models.CollectionResponse:
        """
        Get collection details
        
        Get details of a specific collection.
        
        This endpoint retrieves detailed information about a single
        collection identified by its UUID. The user must have access to the
        collection to view its details.
        
        operationId: collections.retrieve
        endpoint: GET /v1/collections/{id}
        """
        _raw = await self._core.request({
            "method": "GET",
            "path": "/v1/collections/{id}",
            "path_params": {"id": id},
            "query": None,
            "idempotent": True,
        })
        _raw = _raw["results"] if isinstance(_raw, dict) else getattr(_raw, "results", _raw)
        try:
            return models.CollectionResponse.model_validate(_raw)
        except ValidationError:
            return _raw  # type: ignore[return-value]

    async def retrieve_by_name(
        self,
        collection_name: str,
        *,
        owner_id: Optional[Union[str, None]] = None
    ) -> models.CollectionResponse:
        """
        Get a collection by name
        
        Retrieve a collection by its (owner_id, name) combination.
        
        The authenticated user can only fetch collections they own, or, if
        superuser, from anyone.
        
        operationId: collections.retrieveByName
        endpoint: GET /v1/collections/name/{collection_name}
        """
        _raw = await self._core.request({
            "method": "GET",
            "path": "/v1/collections/name/{collection_name}",
            "path_params": {"collection_name": collection_name},
            "query": {"owner_id": owner_id},
            "idempotent": True,
        })
        _raw = _raw["results"] if isinstance(_raw, dict) else getattr(_raw, "results", _raw)
        try:
            return models.CollectionResponse.model_validate(_raw)
        except ValidationError:
            return _raw  # type: ignore[return-value]

    async def update(
        self,
        id: str,
        body: models.UpdateCollectionRequest
    ) -> models.CollectionResponse:
        """
        Update collection
        
        Update an existing collection's configuration.
        
        This endpoint allows updating the name, description, and access settings of an
        existing collection. The user must have appropriate permissions to
        modify the collection.
        
        operationId: collections.update
        endpoint: POST /v1/collections/{id}
        """
        _raw = await self._core.request({
            "method": "POST",
            "path": "/v1/collections/{id}",
            "path_params": {"id": id},
            "query": None,
            "body": body,
            "idempotent": False,
        })
        _raw = _raw["results"] if isinstance(_raw, dict) else getattr(_raw, "results", _raw)
        try:
            return models.CollectionResponse.model_validate(_raw)
        except ValidationError:
            return _raw  # type: ignore[return-value]
