# AUTOGENERATED by nebula-sdks/generator. Do not edit by hand.
# Source: nebula-sdks/openapi/openapi.json

from __future__ import annotations
from typing import Any, Optional, Union
from pydantic import ValidationError
from .. import _models as models
from .._runtime import NebulaCore


class ConnectorsResource:
    def __init__(self, core: NebulaCore) -> None:
        self._core = core

    async def connect(
        self,
        provider: str,
        body: models.ConnectRequest
    ) -> models.WrappedConnectorConnectResponse:
        """
        Start OAuth connection flow
        
        Start the OAuth connection flow for the given external provider. Returns the authorization URL the user should visit to grant Nebula access. After consent the provider redirects back to Nebula and the connection becomes active.
        
        operationId: connectors.connect
        endpoint: POST /v1/connectors/{provider}/connect
        """
        _raw = await self._core.request({
            "method": "POST",
            "path": "/v1/connectors/{provider}/connect",
            "path_params": {"provider": provider},
            "query": None,
            "body": body,
            "idempotent": False,
        })
        try:
            return models.WrappedConnectorConnectResponse.model_validate(_raw)
        except ValidationError:
            return _raw  # type: ignore[return-value]

    async def disconnect(
        self,
        connection_id: str,
        *,
        delete_memories: Optional[bool] = None
    ) -> models.WrappedConnectorDisconnectResponse:
        """
        Disconnect an external data source
        
        Disconnect the named connection, revoking the stored OAuth credentials and stopping future syncs. Optionally pass `delete_memories=true` to also remove every memory this connection had ingested.
        
        operationId: connectors.disconnect
        endpoint: DELETE /v1/connectors/{connection_id}
        """
        _raw = await self._core.request({
            "method": "DELETE",
            "path": "/v1/connectors/{connection_id}",
            "path_params": {"connection_id": connection_id},
            "query": {"delete_memories": delete_memories},
            "idempotent": True,
        })
        try:
            return models.WrappedConnectorDisconnectResponse.model_validate(_raw)
        except ValidationError:
            return _raw  # type: ignore[return-value]

    async def list(
        self,
        collection_id: str
    ) -> models.WrappedListOfConnectorConnectionResponse:
        """
        List active connections for a collection
        
        Return every connector connection associated with the given collection, with encrypted credentials redacted. Useful for showing the user which third-party data sources are wired up to a collection.
        
        operationId: connectors.list
        endpoint: GET /v1/connectors
        """
        _raw = await self._core.request({
            "method": "GET",
            "path": "/v1/connectors",
            "path_params": {},
            "query": {"collection_id": collection_id},
            "idempotent": True,
        })
        try:
            return models.WrappedListOfConnectorConnectionResponse.model_validate(_raw)
        except ValidationError:
            return _raw  # type: ignore[return-value]

    async def list_providers(
        self
    ) -> models.WrappedListOfStr:
        """
        List available connector providers
        
        Return the set of connector provider identifiers (e.g. `google_drive`, `slack`) that this Nebula instance is configured to expose. Pass one of these to `POST /connectors/{provider}/connect` to start an OAuth flow.
        
        operationId: connectors.listProviders
        endpoint: GET /v1/connectors/providers
        """
        _raw = await self._core.request({
            "method": "GET",
            "path": "/v1/connectors/providers",
            "path_params": {},
            "query": None,
            "idempotent": True,
        })
        try:
            return models.WrappedListOfStr.model_validate(_raw)
        except ValidationError:
            return _raw  # type: ignore[return-value]

    async def retrieve(
        self,
        connection_id: str
    ) -> models.WrappedConnectorConnectionResponse:
        """
        Get a single connection by ID
        
        Fetch a single connector connection by its UUID. Returns the connection metadata plus whether the underlying subscription is active. Encrypted credentials are never returned to clients.
        
        operationId: connectors.retrieve
        endpoint: GET /v1/connectors/{connection_id}
        """
        _raw = await self._core.request({
            "method": "GET",
            "path": "/v1/connectors/{connection_id}",
            "path_params": {"connection_id": connection_id},
            "query": None,
            "idempotent": True,
        })
        try:
            return models.WrappedConnectorConnectionResponse.model_validate(_raw)
        except ValidationError:
            return _raw  # type: ignore[return-value]

    async def sync(
        self,
        connection_id: str
    ) -> models.WrappedConnectorSyncResponse:
        """
        Manually trigger a sync
        
        Schedule an immediate sync for an active connection, bypassing the normal cadence. Returns 409 if a sync is already in progress and 400 if the connection isn't in the `active` state.
        
        operationId: connectors.sync
        endpoint: POST /v1/connectors/{connection_id}/sync
        """
        _raw = await self._core.request({
            "method": "POST",
            "path": "/v1/connectors/{connection_id}/sync",
            "path_params": {"connection_id": connection_id},
            "query": None,
            "idempotent": True,
        })
        try:
            return models.WrappedConnectorSyncResponse.model_validate(_raw)
        except ValidationError:
            return _raw  # type: ignore[return-value]
