# AUTOGENERATED by nebula-sdks/generator. Do not edit by hand.
# Source: nebula-sdks/openapi/openapi.json

from __future__ import annotations
from typing import Any, Optional, Union
from pydantic import ValidationError
from .. import _models as models
from .._runtime import NebulaCore


class MemoriesResource:
    def __init__(self, core: NebulaCore) -> None:
        self._core = core

    async def append(
        self,
        id: str,
        body: models.AppendMemoryRequest
    ) -> Any:
        """
        Append content to an engram
        
        Append content to an existing engram.
        
        **For conversation engrams:**
        - Provide `messages` array with content, role, and optional metadata
        - Works like `/conversations/{id}/messages` endpoint
        
        **For document engrams:**
        - Provide either `raw_text` or `chunks` to append additional content
        - Content will be processed and added to the engram
        
        operationId: memories.append
        endpoint: POST /v1/memories/{id}/append
        """
        _raw = await self._core.request({
            "method": "POST",
            "path": "/v1/memories/{id}/append",
            "path_params": {"id": id},
            "query": None,
            "body": body,
            "idempotent": False,
        })
        return _raw

    async def create(
        self,
        body: models.CreateMemoryRequest
    ) -> models.MemoryCreateResponse:
        """
        Create a new memory (conversation or document)
        
        Create a new memory (conversation or document) using clean JSON body.
        
        - Use `collection_id` (UUID)
        - `kind` is optional and inferred from payload shape:
          - If `messages` present -> conversation
          - Otherwise -> document
        - For conversations: provide `messages` array
        - For documents: provide `raw_text` or `chunks`
        - Use `snapshot` for device-memory mode (mutually exclusive with collection_id)
        
        operationId: memories.create
        endpoint: POST /v1/memories
        """
        _raw = await self._core.request({
            "method": "POST",
            "path": "/v1/memories",
            "path_params": {},
            "query": None,
            "body": body,
            "idempotent": False,
        })
        try:
            return models.MemoryCreateResponse.model_validate(_raw)
        except ValidationError:
            return _raw  # type: ignore[return-value]

    async def create_upload(
        self,
        filename: str,
        content_type: str,
        file_size: int
    ) -> models.WrappedPresignedUploadResponse:
        """
        Get presigned URL for large file upload
        
        Get a presigned URL for uploading large files directly to S3.
        
        Use this for files larger than 5MB that cannot be sent inline as base64.
        After uploading, reference the file in memory creation using S3FileReference.
        
        Args:
            filename: Original filename (e.g., "image.jpg")
            content_type: MIME type (e.g., "image/jpeg", "application/pdf")
            file_size: Expected file size in bytes (max 100MB)
        
        Returns:
            dict with:
            - upload_url: Presigned URL for PUT request (expires in 1 hour)
            - upload_headers: Headers that must be sent with the presigned PUT request
            - s3_key: The S3 key to reference in memory creation
            - bucket: S3 bucket name
            - expires_in: Seconds until URL expires
            - max_size: Maximum allowed file size
        
        operationId: memories.createUpload
        endpoint: POST /v1/memories/upload
        """
        _raw = await self._core.request({
            "method": "POST",
            "path": "/v1/memories/upload",
            "path_params": {},
            "query": {"filename": filename, "content_type": content_type, "file_size": file_size},
            "idempotent": False,
        })
        try:
            return models.WrappedPresignedUploadResponse.model_validate(_raw)
        except ValidationError:
            return _raw  # type: ignore[return-value]

    async def delete(
        self,
        id: str
    ) -> models.WrappedGenericBooleanResponse:
        """
        Delete an engram
        
        Delete a specific engram with graph awareness. All chunks corresponding to the
        engram are deleted, and graph components (entities/relationships) are updated
        or deleted based on remaining chunk references from other engrams.
        
        This method now properly handles graph components and maintains graph integrity
        for search operations.
        
        operationId: memories.delete
        endpoint: DELETE /v1/memories/{id}
        """
        _raw = await self._core.request({
            "method": "DELETE",
            "path": "/v1/memories/{id}",
            "path_params": {"id": id},
            "query": None,
            "idempotent": False,
        })
        try:
            return models.WrappedGenericBooleanResponse.model_validate(_raw)
        except ValidationError:
            return _raw  # type: ignore[return-value]

    async def delete_many(
        self,
        body: models.DeleteMemoriesRequest
    ) -> Any:
        """
        Delete one or more engrams
        
        Delete one or more engrams.
        
        This endpoint efficiently handles both single and batch deletions.
        When multiple IDs are provided, it uses optimized batch operations.
        
        Args:
            ids: Either a single UUID or a list of UUIDs to delete
        
        Returns:
            For single deletion: boolean success response
            For batch deletion: detailed results with successful and failed deletions
        
        operationId: memories.deleteMany
        endpoint: POST /v1/memories/delete
        """
        _raw = await self._core.request({
            "method": "POST",
            "path": "/v1/memories/delete",
            "path_params": {},
            "query": None,
            "body": body,
            "idempotent": False,
        })
        return _raw

    async def delete_upload(
        self,
        s3_key: str
    ) -> models.WrappedGenericMessageResponse:
        """
        Delete a previously uploaded S3 file
        
        Delete a file from S3 that was uploaded via a presigned URL.
        Verifies the caller owns the file via S3 object metadata.
        
        operationId: memories.deleteUpload
        endpoint: DELETE /v1/memories/upload
        """
        _raw = await self._core.request({
            "method": "DELETE",
            "path": "/v1/memories/upload",
            "path_params": {},
            "query": {"s3_key": s3_key},
            "idempotent": True,
        })
        try:
            return models.WrappedGenericMessageResponse.model_validate(_raw)
        except ValidationError:
            return _raw  # type: ignore[return-value]

    async def list(
        self,
        *,
        ids: Optional[list[str]] = None,
        cursor: Optional[Union[str, None]] = None,
        limit: Optional[int] = None,
        chunks_limit: Optional[Union[int, None]] = None,
        owner_only: Optional[bool] = None,
        collection_ids: Optional[Union[list[str], None]] = None,
        metadata_filters: Optional[Union[str, None]] = None,
        min_applied_wal_seq: Optional[Union[int, None]] = None
    ) -> models.PaginatedListedEngram:
        """
        List engrams
        
        Returns a cursor-paginated list of engrams the authenticated user
        has access to.
        
        Results can be filtered by providing specific engram IDs or collection IDs.
        Regular users will only see engrams they own or have access to through
        collections. Superusers can see all engrams.
        
        The engrams are returned in order of creation time, most recent
        first. The response includes the engram's text field if available.
        
        operationId: memories.list
        endpoint: GET /v1/memories
        """
        _raw = await self._core.request({
            "method": "GET",
            "path": "/v1/memories",
            "path_params": {},
            "query": {"ids": ids, "cursor": cursor, "limit": limit, "chunks_limit": chunks_limit, "owner_only": owner_only, "collection_ids": collection_ids, "metadata_filters": metadata_filters, "min_applied_wal_seq": min_applied_wal_seq},
            "idempotent": True,
        })
        try:
            return models.PaginatedListedEngram.model_validate(_raw)
        except ValidationError:
            return _raw  # type: ignore[return-value]

    async def recall_workflow(
        self,
        body: Union[models.CursorRecallRequest, models.PredictRecallRequest, models.ResumeRecallRequest, models.EvidenceRecallRequest, models.BootstrapRecallRequest]
    ) -> models.WorkflowRecallResponse:
        """
        Recall workflow patterns by intent
        
        Workflow-pattern recall over 5 intents.
        
        * ``cursor`` -- match the caller's anchor against pattern
          canonical states, return ranked patterns + position.
        * ``predict`` -- like cursor but include the predicted next
          trace from each pattern's canonical instance.
        * ``resume`` -- like cursor, biased toward longer patterns.
        * ``evidence`` -- expand a specific pattern via
          ``hydrate_pattern``.
        * ``bootstrap`` -- top-K patterns by confidence with no anchor.
        
        operationId: memories.recallWorkflow
        endpoint: POST /v1/memories/workflow/recall
        """
        _raw = await self._core.request({
            "method": "POST",
            "path": "/v1/memories/workflow/recall",
            "path_params": {},
            "query": None,
            "body": body,
            "idempotent": False,
        })
        try:
            return models.WorkflowRecallResponse.model_validate(_raw)
        except ValidationError:
            return _raw  # type: ignore[return-value]

    async def retrieve(
        self,
        id: str
    ) -> models.WrappedEngram:
        """
        Retrieve an engram
        
        Retrieves detailed information about a specific engram by its
        ID.
        
        This endpoint returns the engram's metadata, status, and system information. It does not
        return the engram's content - use the `/engrams/{id}/download` endpoint for that.
        
        Users can only retrieve engrams they own or have access to through collections.
        Superusers can retrieve any engram.
        
        operationId: memories.retrieve
        endpoint: GET /v1/memories/{id}
        """
        _raw = await self._core.request({
            "method": "GET",
            "path": "/v1/memories/{id}",
            "path_params": {"id": id},
            "query": None,
            "idempotent": True,
        })
        try:
            return models.WrappedEngram.model_validate(_raw)
        except ValidationError:
            return _raw  # type: ignore[return-value]

    async def search(
        self,
        body: models.MemorySearchRequest
    ) -> Any:
        """
        Search memories
        
        Perform a search query across your memories.
        
        **Standard mode** (collection_ids or readable-scope search): returns hierarchical MemoryRecall
        with semantics, episodes, procedures, and sources.
        
        **Snapshot mode** (snapshot field): returns graph-search results with
        {entities, relationships} from stateless in-memory traversal.
        
        operationId: memories.search
        endpoint: POST /v1/memories/search
        """
        _raw = await self._core.request({
            "method": "POST",
            "path": "/v1/memories/search",
            "path_params": {},
            "query": None,
            "body": body,
            "idempotent": False,
        })
        return _raw

    async def update(
        self,
        id: str,
        body: models.UpdateMemoryRequest,
        *,
        collection_id: Optional[Union[str, None]] = None
    ) -> models.WrappedEngram:
        """
        Update a memory
        
        Update memory-level properties including name, metadata, and collection associations.
        
        This endpoint allows updating properties of an entire memory (document or conversation)
        without modifying its content:
        - **name**: Updates the authoritative engram title
        - **metadata**: Can replace or merge with existing metadata
        - **collection_ids**: Updates authoritative engram collection associations
        
        Users can only update memories they own or have access to through collections.
        At least one collection association must be maintained.
        
        If collection_id is provided and the engram is shared across collections, a copy-on-write
        will be performed to create a collection-specific copy before modification.
        
        operationId: memories.update
        endpoint: PATCH /v1/memories/{id}
        """
        _raw = await self._core.request({
            "method": "PATCH",
            "path": "/v1/memories/{id}",
            "path_params": {"id": id},
            "query": {"collection_id": collection_id},
            "body": body,
            "idempotent": False,
        })
        try:
            return models.WrappedEngram.model_validate(_raw)
        except ValidationError:
            return _raw  # type: ignore[return-value]
