# AUTOGENERATED by nebula-sdks/generator. Do not edit by hand.
# Source: nebula-sdks/openapi/openapi.json

from __future__ import annotations
from typing import Any, Optional, Union
from pydantic import ValidationError
from .. import _models as models
from .._runtime import NebulaCore


class SnapshotsResource:
    def __init__(self, core: NebulaCore) -> None:
        self._core = core

    async def export(
        self,
        body: models.SnapshotExportRequest
    ) -> models.WrappedSnapshotEnvelope:
        """
        Export a collection snapshot
        
        Export a collection's full graph state as a
        portable SnapshotEnvelope.
        
        operationId: snapshots.export
        endpoint: POST /v1/device-memory/snapshot/export
        """
        _raw = await self._core.request({
            "method": "POST",
            "path": "/v1/device-memory/snapshot/export",
            "path_params": {},
            "query": None,
            "body": body,
            "idempotent": True,
        })
        try:
            return models.WrappedSnapshotEnvelope.model_validate(_raw)
        except ValidationError:
            return _raw  # type: ignore[return-value]

    async def import_(
        self,
        body: models.SnapshotImportRequest
    ) -> models.WrappedSnapshotImportResult:
        """
        Import a snapshot into an ephemeral collection
        
        Import a SnapshotEnvelope into an ephemeral
        collection. Returns the ephemeral collection UUID.
        
        operationId: snapshots.import
        endpoint: POST /v1/device-memory/snapshot/import
        """
        _raw = await self._core.request({
            "method": "POST",
            "path": "/v1/device-memory/snapshot/import",
            "path_params": {},
            "query": None,
            "body": body,
            "idempotent": False,
        })
        try:
            return models.WrappedSnapshotImportResult.model_validate(_raw)
        except ValidationError:
            return _raw  # type: ignore[return-value]
