# AUTOGENERATED by nebula-sdks/generator. Do not edit by hand.
# Source: nebula-sdks/openapi/openapi.json + nebula-sdks/config/sdk-resource-map.yaml

from __future__ import annotations
from typing import Optional
from . import _models as models
from ._runtime import NebulaCore, ClientOptions
from .resources.client import ClientResource
from .resources.collections import CollectionsResource
from .resources.connectors import ConnectorsResource
from .resources.memories import MemoriesResource
from .resources.snapshots import SnapshotsResource


class NebulaClient:
    def __init__(self, options: Optional[ClientOptions] = None) -> None:
        self._core = NebulaCore(options)
        self.client: ClientResource = ClientResource(self._core)
        self.collections: CollectionsResource = CollectionsResource(self._core)
        self.connectors: ConnectorsResource = ConnectorsResource(self._core)
        self.memories: MemoriesResource = MemoriesResource(self._core)
        self.snapshots: SnapshotsResource = SnapshotsResource(self._core)

    async def aclose(self) -> None:
        await self._core.aclose()

    async def __aenter__(self) -> "NebulaClient":
        return self

    async def __aexit__(self, *args: object) -> None:
        await self.aclose()
