# AUTOGENERATED by nebula-sdks/generator. Do not edit by hand.
# Source: nebula-sdks/config/dx-extensions.yaml

from __future__ import annotations
from collections.abc import Mapping
from typing import Any
from ._client import NebulaClient


def _unwrap(value: Any) -> Any:
    """Strip a `results` envelope if present."""
    if isinstance(value, Mapping) and "results" in value:
        return value["results"]
    if hasattr(value, "results"):
        return value.results
    return value


class NebulaDX(NebulaClient):
    """Generated DX layer: simple unwrap/passthrough methods.
    The handwritten `Nebula` class extends this with complex methods.
    """

    async def get_memory(self, id: str) -> Any:
        """Retrieve a single memory by id and return just the data. (generated)."""
        return _unwrap(await self.memories.retrieve(id))

    async def update_memory(self, **kwargs: Any) -> Any:
        """Update a memory by id; returns the updated record. (generated)."""
        return _unwrap(await self.memories.update(**kwargs))

    async def health_check(self) -> Any:
        """Liveness probe with the wire envelope unwrapped. (generated)."""
        return _unwrap(await self.client.health())

    async def create_collection(self, **kwargs: Any) -> Any:
        """unwrap -> collections.create (generated)."""
        return _unwrap(await self.collections.create(**kwargs))

    async def get_collection(self, id: str) -> Any:
        """unwrap -> collections.retrieve (generated)."""
        return _unwrap(await self.collections.retrieve(id))

    async def get_collection_by_name(self, **kwargs: Any) -> Any:
        """unwrap -> collections.retrieveByName (generated)."""
        return _unwrap(await self.collections.retrieve_by_name(**kwargs))

    async def list_collections(self, **kwargs: Any) -> Any:
        """unwrap -> collections.list (generated)."""
        return _unwrap(await self.collections.list(**kwargs))

    async def update_collection(self, **kwargs: Any) -> Any:
        """unwrap -> collections.update (generated)."""
        return _unwrap(await self.collections.update(**kwargs))

    async def list_providers(self) -> Any:
        """unwrap -> connectors.listProviders (generated)."""
        return _unwrap(await self.connectors.list_providers())

    async def get_connection(self, connection_id: str) -> Any:
        """unwrap -> connectors.retrieve (generated)."""
        return _unwrap(await self.connectors.retrieve(connection_id))

    async def trigger_sync(self, connection_id: str) -> Any:
        """unwrap -> connectors.sync (generated)."""
        return _unwrap(await self.connectors.sync(connection_id))

    async def get_upload_url(self, **kwargs: Any) -> Any:
        """unwrap -> memories.createUpload (generated)."""
        return _unwrap(await self.memories.create_upload(**kwargs))

    async def export_snapshot(self, **kwargs: Any) -> Any:
        """unwrap -> snapshots.export (generated)."""
        return _unwrap(await self.snapshots.export(**kwargs))

    async def import_snapshot(self, **kwargs: Any) -> Any:
        """unwrap -> snapshots.import (generated)."""
        return _unwrap(await self.snapshots.import_(**kwargs))
